blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blogapp import urls as blog_urls
from userapp import urls as user_urls
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include(blog_urls, namespace='blog')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^user/', include(user_urls, namespace='user')),
    url(r'^captcha/', include('captcha.urls')),  # 增加这一行
    url(r'^uploads/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))

]
# 配置富文本的上传路径
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogapp/urls.py
from django.conf.urls import url, include
from blogapp import views
from blogapp.uploads import upload_image
from rest_framework.routers import DefaultRouter

publisherlist = views.PublisherList.as_view(
    {
        'get': 'list',
        'post': 'create'
    }
)

publisherdetail = views.PublisherList.as_view(
    {
        'get': 'retrieve',
        'put': 'update',
        'patch': 'partial_update',
        # 'delete': 'destory'
    }
)

router = DefaultRouter()
router.register(r'publish',views.PublisherList)


urlpatterns = [
    url(r'^index/(\d*)', views.index, name='index'),
    url(r'^search/', views.search, name='search'),
    url(r'^list/(\d*)', views.list, name='list'),
    url(r'^show/(\d*)', views.show, name='show'),
    url(r'^blog_list/(?P<bid>\d*)', views.category_list, name='blog_list'),
    url(r'^comment/', views.comment, name='comment'),
    url(r'^tags_list/(?P<tid>\d*)', views.category_list, name='tags_list'),
    url(r'^a/', views.a),
    url(r'^ifcom/', views.ifcom),
    url(r'^upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
    url(r'^write/', views.write, name='write'),
    # url(r'^publisher/$', views.PublisherList.as_view()),
    # url(r'^publisher/(?P<pk>[0-9]+)/', views.PublisherDetail.as_view( )),
    url(r'^publisher/$', publisherlist),
    url(r'^publisher/(?P<pk>[0-9]+)/', publisherdetail),
    url(r'^',include(router.urls))

]

blog/blogapp/models.py
from django.db import models
from userapp.models import BlogUser
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class Banner(models.Model):
    title = models.CharField('标题',max_length=50)
    img = models.ImageField('轮播图',upload_to='static/images/banner')
    img_url = models.URLField('图片链接',max_length=100)
    index = models.IntegerField('索引')
    is_active=models.BooleanField('是否激活',default=False)
    operator = models.ForeignKey(BlogUser)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='轮播图'
        verbose_name_plural = verbose_name
class BlogCategory(models.Model):
    name = models.CharField('分类名称',max_length=20,default='')
    class Meta:
        verbose_name='博客分类'
        verbose_name_plural = verbose_name
    def __str__(self):
        return self.name
class Tags(models.Model):
    name = models.CharField('标签名称',max_length=20,default='')
    class Meta:
        verbose_name='标签'
        verbose_name_plural=verbose_name
    def __str__(self):
        return self.name
class Post(models.Model):
    #  ！！！！这里的用户到底是如何注册进入的，为啥我记得是老师注册的超级用户呢
    user = models.ForeignKey(BlogUser,verbose_name='作者')
    category=models.ForeignKey(BlogCategory,verbose_name='博客分类',default='')
    tags=models.ManyToManyField(Tags,verbose_name='标签')
    title = models.CharField('标题',max_length=50)
    content = RichTextUploadingField('内容')
    pub_date = models.DateTimeField('发布日期',auto_now_add=True)
    img = models.ImageField('博客封面',upload_to='static/images/post',default=None)
    views_num = models.IntegerField('浏览量',default=0)
    is_recommend=models.BooleanField('是否推荐博客',default=False)
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='博客'
        verbose_name_plural=verbose_name
class Comment(models.Model):
    post = models.ForeignKey(Post,verbose_name='博客')
    views = models.IntegerField('评论的点击量',default=0)  # 这是一个 用户评论被点击的数字
    user = models.ForeignKey(BlogUser,verbose_name='作者')
    pub_date = models.DateTimeField('发布时间',auto_now_add=True)
    content = models.TextField('内容')
    def __str__(self):
        return self.content
    class Meta:
        verbose_name='评论'
        verbose_name_plural=verbose_name
class FriendlyLink(models.Model):
    title = models.CharField('标题',max_length=50)
    link = models.URLField('链接',max_length=100,default='')
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='友情链接'
        verbose_name_plural=verbose_name
class Poster(models.Model):
    title = models.CharField('标题',max_length=50)
    link = models.URLField('广告地址',max_length=100,default='')
    img = models.ImageField('图片',upload_to='static/images/poster')
    def __str__(self):
        return self.title
    class Meta:
        verbose_name='广告位'
        verbose_name_plural=verbose_name

blog/templates/comment_poster.html
<div class="widget widget_hot">
    <h3>最新评论文章</h3>
    <ul>
        {% for post in comment_list %}
            <li><a title="{{ post.title }}" href="{% url 'blog:show' post.id %}"><span
                    class="thumbnail">

                    <img class="thumb"
                         data-original="/media/{{ post.img }}"
                         src="/media/{{ post.img }}"
                         alt="{{ post.title }}" style="display: block;">
                </span><span class="text">{{ post.title }}</span><span class="muted"><i
                    class="glyphicon glyphicon-time"></i>
                    {{ post.pub_date }} <br>
                </span><span class="muted"><i
                    class="glyphicon glyphicon-eye-open"></i>{{ post.views_num }}</span></a></li>

        {% endfor %}
    </ul>

</div>
{% for poster in poster_list %}
    <div class="widget widget_sentence">
        <a href='{{ poster.link }}' target="_blank" rel="nofollow" title="{{ poster.title }}">
            <img style="width: 100%" src="/{{ poster.img }}"
                 alt="{{ poster.title }}"></a>
    </div>
{% endfor %}
<div class="widget widget_sentence">
    <h3>友情链接</h3>
    <div class="widget-sentence-link">
        {% for flink in friendly_link_list %}
            <a href="{{ flink.link }}" title="{{ flink.title }}" target="_blank">{{ flink.title }}</a>&nbsp;
            &nbsp;&nbsp;
        {% endfor %}
    </div>
</div>

blog/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <section class="container">
        <div class="content-wrap">
            <div class="content">
                {# 轮播图部分 #}
                <div id="focusslide" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#focusslide" data-slide-to="0" class="active"></li>
                        <li data-target="#focusslide" data-slide-to="1"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        {% for banner in banner_list %}
                            {% if banner.is_active %}
                                <div class="item active">
                                    <a href="#" target="_blank" title="{{ banner.title }}">
                                        <img src="/{{ banner.img }}"
                                             alt="{{ banner.title }}"
                                             class="img-responsive"></a>
                                </div>
                            {% else %}
                                <div class="item">
                                    <a href="#" target="_blank" title="{{ banner.title }}">
                                        <img src="/{{ banner.img }}"
                                             alt="{{ banner.title }}"
                                             class="img-responsive"></a>
                                </div>
                            {% endif %}
                        {% endfor %}


                    </div>
                    <a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span
                            class="sr-only">上一个</span> </a> <a class="right carousel-control" href="#focusslide"
                                                               role="button" data-slide="next" rel="nofollow"> <span
                        class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span
                        class="sr-only">下一个</span> </a></div>
                {# 这里是博客推荐部分 #}
                {% for post in recomment_list %}
                    <article class="excerpt-minic excerpt-minic-index">
                        <h2><span class="red">【推荐】</span><a target="_blank" href="{% url 'blog:show' post.id %}"
                                                            title="{{ post.title }}">{{ post.title }}</a>
                        </h2>
                        <p class="note" id="recommend">{{ post.content|safe }}</p>
                    </article>
                {% endfor %}



                <div class="title">
                    <h3>最新发布</h3>
                    <div class="more">
                        {% for bl in blogcategory %}
                            <a href="{% url 'blog:blog_list' bid=bl.id %}" title="{{ bl.name }}">{{ bl.name }}</a>
                        {% endfor %}
                    </div>
                </div>
                {# 这里是博客的最近发布状态 #}
                {% include 'post_list.html' %}


                <nav class="pagination">
                    <ul>
                        {% if lp == 1 %}
                            <li class="prev-page"><a href="{% url 'blog:list' pIndex|add:-1 %}">上一页</a></li>
                        {% endif %}

                        {% for page_num in page_num_list %}
                            <li class="active"><a href="/blog/list/{{ page_num }}">{{ page_num }}</a></li>
                        {% endfor %}

                        {% if np == 1 %}
                            <li class="next-page"><a href="{% url 'blog:list' pIndex|add:1 %}">下一页</a></li>
                        {% endif %}

                        <li><span>共 {{ all }} 页</span></li>
                    </ul>
                </nav>
            </div>
        </div>
        <aside class="sidebar">
            <div class="fixed">
                <div class="widget widget-tabs">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab"
                                                                  data-toggle="tab">统计信息</a></li>
                        <li role="presentation"><a href="#contact" aria-controls="contact" role="tab"
                                                   data-toggle="tab">联系站长</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane contact active" id="notice">
                            <h2>日志总数:
                                {{ blog_all }}篇
                            </h2>
                            <h2>网站运行:
                                <span id="sitetime">88天 </span></h2>
                        </div>
                        <div role="tabpanel" class="tab-pane contact" id="contact">
                            <h2>QQ:
                                <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=577211782&amp;site=qq&amp;menu=yes"
                                   target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom" title=""
                                   data-original-title="QQ:577211782">577211782</a>
                            </h2>
                            <h2>Email:
                                <a href="mailto:577211782@qq.com" target="_blank" data-toggle="tooltip" rel="nofollow"
                                   data-placement="bottom" title="" data-original-title="Email:577211782@qq.com">577211782@qq.com</a>
                            </h2>
                        </div>
                    </div>
                </div>
                {# 这里shi 博客的搜索功能 #}
                {% include 'search.html' %}
            </div>

            {# 这里是 文章最新评论的地方 #}
            {% include 'comment_poster.html' %}
        </aside>
    </section>
{% endblock content %}

<script src="/static/js/bootstrap.min.js"></script>
{#<script src="/static/js/jquery.ias.js"></script>#} {# 这里是js的一个插件，作用是向上刷新，显示多次以上的内容 #}
<script src="/static/js/scripts.js"></script>
</body>
</html>

blog/templates/list.html
{% extends 'base.html' %}

{% block title %}博客列表页{% endblock %}
{% block content %}
    <section class="container">
        <div class="content-wrap">
            <div class="content">
                <div class="title">
                    <h3 style="line-height: 1.3">{{ title }}</h3>
                </div>
                {% include 'post_list.html' %}

                <nav class="pagination">
                    <ul>

                        {% if lp == 1 %}
                            <li class="prev-page"><a href="{% url 'blog:list' pIndex|add:-1 %}">上一页</a></li>
                        {% endif %}


                        {% for page_num in page_num_list %}
                            <li class="active"><a href="/blog/list/{{ page_num }}">{{ page_num }}</a></li>
                        {% endfor %}

                        {% if np == 1 %}
                            <li class="next-page"><a href="{% url 'blog:list' pIndex|add:1 %}">下一页</a></li>
                        {% endif %}

                        <li><span>共 {{ all }} 页</span></li>
                    </ul>
                </nav>
            </div>
        </div>
        <aside class="sidebar">
            <div class="fixed">
                {% include 'search.html' %}
                <div class="widget widget_sentence">
                    <h3>标签云</h3>
                    <div class="widget-sentence-content">
                        <ul class="plinks ptags">
                            {% for tag in tags_list %}
                                <li><a href="{% url 'blog:tags_list' tag.id %}" title="{{ tag.name }}"
                                       draggable="false">{{ tag.name }}
                                    <span
                                            class="badge">{{ tag.post_set.count }}</span></a></li>

                            {% endfor %}


                        </ul>
                    </div>
                </div>
            </div>
            {% include 'comment_poster.html' %}


        </aside>
    </section>
{% endblock %}
<body class="user-select">


<script src="/static/js/bootstrap.min.js"></script>
{#<script src="/static/js/jquery.ias.js"></script>#}
<script src="/static/js/scripts.js"></script>
</body>
</html>

blog/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %} {# 这个表示什么意思啊，是不是吧静态文件加载到自己的html文件中 #}
{% block title %}登录{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="/user/login/" method="post">

                {% if msg %}
                    <div class="alert alert-warning">{{ msg }}</div>
                {% endif %}
                {% csrf_token %}
                <h2 class="text-center">欢迎登录</h2>
                <div class="form-group">
                    {{ login_form.username.label_tag }}
                    {{ login_form.username }}
                </div>
                <div class="form-group">
                    {{ login_form.password.label_tag }}
                    {{ login_form.password }}
                </div>
                <div class="form-group">
                    {{ login_form.captcha.errors }}
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha }}<a href="">换一张</a>
                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

blog/templates/post_list.html
{% for post in page_list %}
{#    <img src="/static/images/bad_img/bad_img.png" alt="1234123412341234123412341234123" id="999">#}
    <article class="excerpt excerpt-1" style="">
{#        <img src="/static/bad_img/bad_img.png" alt="1234123412341234123412341234123" id="999">#}

        <a class="focus" href="{% url 'blog:show' post.id %}" title="{{ post.title }}"
           target="_blank">
            <img class="thumb"
                 data-original="/media/{{ post.img }}"
                 src="/media/{{ post.img }}"
                 alt="{{ post.title }}" style="display: inline;">
        </a>
        <header><a class="cat" href="{% url 'blog:show' post.id %}" title="{{ post.title }}">{{ post.title }}<i></i></a>
            <h2><a href="{% url 'blog:show' post.id %}" title="{{ post.title }}"
                   target="_blank">{{ post.title }}</a>
            </h2>
        </header>
        <p class="meta">
            <time class="time"><i class="glyphicon glyphicon-time"></i>{{ post.pub_date }}</time>
            <span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{ post.views_num }}</span>
            <a
                    class="comment"
                    href="{% url 'blog:show' post.id %}"
                    title="评论"
                    target="_blank"><i
                    class="glyphicon glyphicon-comment"></i> {{ post.comment_set.count }}</a>
        </p>
        <p class="note">{{ post.content|safe }}</p>
    </article>
{% endfor %}

blog/templates/search.html
<div class="widget widget_search">
    <form class="navbar-form" action="{% url 'blog:search' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字"
                   maxlength="15" autocomplete="off">
            <span class="input-group-btn">
            <button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
            </span></div>
    </form>
</div>

blog/templates/show.html
{% extends 'base.html' %}
{% block title %}博客详情页{% endblock %}
<script src="/static/js/editor/kindeditor/kindeditor-all-min.js"></script>
<script src="/static/js/editor/kindeditor/lang/zh-CN.js"></script>
<script src="/static/js/editor/kindeditor/themes/default/default.css"></script>
{% block jquery %}
    <script src="/static/js/editor/kindeditor/kindeditor-all-min.js"></script>
    <script src="/static/js/editor/kindeditor/lang/zh-CN.js"></script>
    <script src="/static/js/editor/kindeditor/themes/default/default.css"></script>
    <script>
        KindEditor.ready(function (k) {
            window.editor = k.create('#editor_id', {
                resizeType: 1,
                allowPreviewEmoticons: false,
                allowImageRemote: false,
                {#处理url#}
                uploadJson: '/blog/upload/kindeditor',

            });
        })



    </script>
{% endblock %}

{% block content %}
    <section class="container">
        <div class="content-wrap">
            <div class="content">
                <header class="article-header">
                    <h1 class="article-title"><a href="http://www.muzhuangnet.com/show/269.html"
                                                 title="{{ post.title }}">{{ post.title }}</a></h1>
                    <div class="article-meta"> <span class="item article-meta-time">
          <time class="time" data-toggle="tooltip" data-placement="bottom" title=""
                data-original-title="发表时间：{{ post.pub_date }}"><i
                  class="glyphicon glyphicon-time"></i> {{ post.pub_date }}</time>
          </span> <span class="item article-meta-source" data-toggle="tooltip" data-placement="bottom" title=""
                        data-original-title="来源：木庄网络博客"><i class="glyphicon glyphicon-globe"></i> 木庄网络博客</span> <span
                            class="item article-meta-category" data-toggle="tooltip" data-placement="bottom" title=""
                            data-original-title="MZ-NetBlog主题"><i class="glyphicon glyphicon-list"></i> <a
                            href="http://www.muzhuangnet.com/list/mznetblog/"
                            title="{{ post.category }}">{{ post.category }}</a></span> <span
                            class="item article-meta-views"
                            data-toggle="tooltip"
                            data-placement="bottom" title=""
                            data-original-title="浏览量：{{ post.views_num }}"><i
                            class="glyphicon glyphicon-eye-open"></i> {{ post.views_num }}</span> <span
                            class="item article-meta-comment"
                            data-toggle="tooltip"
                            data-placement="bottom" title=""
                            data-original-title="评论量"><i
                            class="glyphicon glyphicon-comment"></i> {{ post.comment_set.count }}</span></div>
                </header>
                <article class="article-content">
                    {#                    <p><img data-original="/{{ post.img }}"#}
                    {#                            src="/{{ post.img }}" alt=""/></p>#}
                    {#                    <p>{{ post.content }}</p>#}
                    {{ post.content|safe }}
                    <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#"
                                                                                                      class="bds_qzone"
                                                                                                      data-cmd="qzone"
                                                                                                      title="分享到QQ空间"></a><a
                            href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq"
                                                                                               data-cmd="tqq"
                                                                                               title="分享到腾讯微博"></a><a
                            href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#"
                                                                                               class="bds_tieba"
                                                                                               data-cmd="tieba"
                                                                                               title="分享到百度贴吧"></a><a
                            href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a></div>

                    <script>                  window._bd_share_config = {
                        "common": {
                            "bdSnsKey": {},
                            "bdText": "",
                            "bdMini": "2",
                            "bdMiniList": false,
                            "bdPic": "",
                            "bdStyle": "1",
                            "bdSize": "32"
                        }, "share": {}
                    };
                    with (document) 0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api//static/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
                </article>


                <div class="article-tags">标签：
                    {% for tag in tags %}
                        <a href="http://www.muzhuangnet.com/tags/list/2/" rel="tag">{{ tag.name }}</a>
                    {% endfor %}
                </div>


                <div class="relates">
                    <div class="title">
                        <h3>相关推荐</h3>
                    </div>
                    <ul>
                        {% for recomment in recomment_list %}
                            <li><a href="http://www.muzhuangnet.com/show/269.html" title="">{{ recomment.title }}</a>
                            </li>
                        {% endfor %}


                    </ul>
                </div>
                <div class="title" id="comment">
                    <h3>评论</h3>
                </div>
                <div id="respond">
                    <form id="comment-form" name="comment-form" action="{% url 'blog:comment' %}" method="POST">
                        {# TODO：这里的action应该怎么写呢？？？？？？？？？？？？,{% url 'blog:comment' %}为什么加入这个之后，再进行页面跳转时会报错 #}
                        {% csrf_token %}
                        <div class="comment">
                            <input name="nickname" id="" class="form-control" size="22" placeholder="您的昵称（必填）"
                                   maxlength="15"
                                   autocomplete="off" tabindex="1" type="text">
                            <input name="post_id" type="hidden" value="{{ post.id }}">
                            <input name="emial" id="" class="form-control" size="22" placeholder="您的网址或邮箱（非必填）"
                                   maxlength="58" autocomplete="off" tabindex="2" type="text">
                            <div class="comment-box">
                                {#                                id="comment-textarea"#}
                                <textarea class="comment-textarea" placeholder="您的评论或留言（必填）" name="comment-textarea"
                                          id="editor_id"
                                          cols="100%" rows="3" tabindex="3"></textarea>
                                <div class="comment-ctrl">
                                    <div class="comment-prompt" style="display: none;"><i
                                            class="fa fa-spin fa-circle-o-notch"></i> <span class="comment-prompt-text">评论正在提交中...请稍后</span>
                                    </div>
                                    <div class="comment-success" style="display: none;"><i class="fa fa-check"></i>
                                        <span class="comment-prompt-text">评论提交成功...</span></div>
                                    <button type="submit" name="comment-submit" id="comment-submit" tabindex="4">评论
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
                <div id="postcomments">
                    <ol id="comment_list" class="commentlist">
                        {% for com in com_list %}
                            <li class="comment-content"><span class="comment-f">#{{ forloop.counter }}</span>
                                <div class="comment-main"><p><a class="address" href="http://www.muzhuangnet.com/"
                                                                rel="nofollow"
                                                                target="_blank">{{ com.user.username }}</a><span
                                        class="time">{{ com.pub_date }}</span><br>{{ com.content|safe }}
                                </p></div>
                            </li>
                        {% endfor %}


                    </ol>
                </div>
            </div>
        </div>
        <aside class="sidebar">
            <div class="fixed">
                <div class="widget widget-tabs">
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab"
                                                                  data-toggle="tab" draggable="false">统计信息</a></li>
                        <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab"
                                                   draggable="false">联系站长</a></li>
                    </ul>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane contact active" id="notice">
                            <h2>日志总数:
                                {{ blog_all }}篇
                            </h2>
                            <h2>网站运行:
                                <span id="sitetime">88天 </span></h2>
                        </div>
                        <div role="tabpanel" class="tab-pane contact" id="contact">
                            <h2>QQ:
                                <a href="http://wpa.qq.com/msgrd?v=3&amp;uin=577211782&amp;site=qq&amp;menu=yes"
                                   target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom" title=""
                                   draggable="false" data-original-title="QQ:577211782">577211782</a>
                            </h2>
                            <h2>Email:
                                <a href="mailto:577211782@qq.com" target="_blank" data-toggle="tooltip" rel="nofollow"
                                   data-placement="bottom" title="" draggable="false"
                                   data-original-title="Email:577211782@qq.com">577211782@qq.com</a></h2>
                        </div>
                    </div>
                </div>
                {% include 'search.html' %}
            </div>
            {% include 'comment_poster.html' %}

        </aside>
    </section>
{% endblock content %}


blog/templates/write.html
{% extends 'base.html' %}
{% block jquery %}
    <script src="/static/js/editor/kindeditor/kindeditor-all-min.js"></script>
    <script src="/static/js/editor/kindeditor/lang/zh-CN.js"></script>
    <script src="/static/js/editor/kindeditor/themes/default/default.css"></script>
    <script>
        KindEditor.ready(function (k) {
            window.editor = k.create('#editor_id', {
                resizeType: 1,
                allowPreviewEmoticons: false,
                allowImageRemote: false,
                {#处理url#}
                uploadJson: '/blog/upload/kindeditor',

            });
        })
    </script>
{% endblock %}
{% block content %}
    <form action="{% url 'blog:write' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        标题：<input type="text" name="title"><br>

        分类：<select name="cate" id="">
        {% for foo in cate %}
            <option value="{{ foo.id }}">{{ foo.name }}</option>
        {% endfor %}</select>


        标签：<select name="tag" id="">
        {% for tag in tags %}
            <option value="{{ tag.id }}">{{ tag.name }}</option>

        {% endfor %}

    </select>
        <textarea placeholder="您的内容" name="con" id="editor_id"></textarea>
        <input type="file" name="img">
        <button type="submit">提交</button>
        <button type="reset">重置</button>
    </form>
{% endblock content %}